#!/bin/bash

# https://tldp.org/HOWTO/Bash-Prompt-HOWTO/x329.html

chr="│"
msg="${@}" 
[[ -z "${1}" ]] && msg=" xXXxxXx "

declare -a bgList=( 
  "40m" "41m" "42m" "43m"
  "44m" "45m" "46m" "47m"
)

declare -a fgList=(
  "    m" "   1m"
  "  30m" "1;30m"
  "  31m" "1;31m"
  "  32m" "1;32m"
  "  33m" "1;33m"
  "  34m" "1;34m"
  "  35m" "1;35m"
  "  36m" "1;36m" 
  "  37m" "1;37m"
)

len=$((${#msg} - 1))
minus=1

if [[ $((${#msg} % 2)) -eq 0 ]]; then 
  len=${#msg} && minus=2
fi

padLeft=$(for i in $(seq $((len / 2 - ${minus}))); do echo -n " "; done)
padRight=$(for i in $(seq $((len / 2 - 1))); do echo -n " "; done)

echo -en "\n\x1b[4m       "
for bg in "${bgList[@]}"; do 
  echo -n "${chr}${padLeft}${bg}${padRight}"
done
echo -e "\x1b[24m"

for fg in "${fgList[@]}"; do
  current="${fg// /}"

  echo -en " ${fg} ${chr}"
  for bg in "${bgList[@]}"; do
    echo -en "\x1b[${current}\x1b[${bg}${msg}\x1b[0m${chr}"
  done
  echo
done
